// megafunction wizard: %LPM_MUX%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: lpm_mux 

// ============================================================
// File Name: element_mux_32x2.v
// Megafunction Name(s):
// 			lpm_mux
//
// Simulation Library Files(s):
// 			lpm
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 9.1 Build 222 10/21/2009 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2009 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//lpm_mux DEVICE_FAMILY="Stratix III" LPM_SIZE=2 LPM_WIDTH=32 LPM_WIDTHS=1 data result sel
//VERSION_BEGIN 9.1 cbx_lpm_mux 2009:10:21:21:22:16:SJ cbx_mgl 2009:10:21:21:37:49:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = lut 11 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  element_mux_32x2_mux
	( 
	data,
	result,
	sel) /* synthesis synthesis_clearbox=1 */;
	input   [63:0]  data;
	output   [31:0]  result;
	input   [0:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [63:0]  data;
	tri0   [0:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire	wire_l1_w0_n0_mux_dataout;
	wire	wire_l1_w10_n0_mux_dataout;
	wire	wire_l1_w11_n0_mux_dataout;
	wire	wire_l1_w12_n0_mux_dataout;
	wire	wire_l1_w13_n0_mux_dataout;
	wire	wire_l1_w14_n0_mux_dataout;
	wire	wire_l1_w15_n0_mux_dataout;
	wire	wire_l1_w16_n0_mux_dataout;
	wire	wire_l1_w17_n0_mux_dataout;
	wire	wire_l1_w18_n0_mux_dataout;
	wire	wire_l1_w19_n0_mux_dataout;
	wire	wire_l1_w1_n0_mux_dataout;
	wire	wire_l1_w20_n0_mux_dataout;
	wire	wire_l1_w21_n0_mux_dataout;
	wire	wire_l1_w22_n0_mux_dataout;
	wire	wire_l1_w23_n0_mux_dataout;
	wire	wire_l1_w24_n0_mux_dataout;
	wire	wire_l1_w25_n0_mux_dataout;
	wire	wire_l1_w26_n0_mux_dataout;
	wire	wire_l1_w27_n0_mux_dataout;
	wire	wire_l1_w28_n0_mux_dataout;
	wire	wire_l1_w29_n0_mux_dataout;
	wire	wire_l1_w2_n0_mux_dataout;
	wire	wire_l1_w30_n0_mux_dataout;
	wire	wire_l1_w31_n0_mux_dataout;
	wire	wire_l1_w3_n0_mux_dataout;
	wire	wire_l1_w4_n0_mux_dataout;
	wire	wire_l1_w5_n0_mux_dataout;
	wire	wire_l1_w6_n0_mux_dataout;
	wire	wire_l1_w7_n0_mux_dataout;
	wire	wire_l1_w8_n0_mux_dataout;
	wire	wire_l1_w9_n0_mux_dataout;
	wire  [63:0]  data_wire;
	wire  [31:0]  result_wire_ext;
	wire  [0:0]  sel_wire;

	assign		wire_l1_w0_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[32] : data_wire[0];
	assign		wire_l1_w10_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[42] : data_wire[10];
	assign		wire_l1_w11_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[43] : data_wire[11];
	assign		wire_l1_w12_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[44] : data_wire[12];
	assign		wire_l1_w13_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[45] : data_wire[13];
	assign		wire_l1_w14_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[46] : data_wire[14];
	assign		wire_l1_w15_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[47] : data_wire[15];
	assign		wire_l1_w16_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[48] : data_wire[16];
	assign		wire_l1_w17_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[49] : data_wire[17];
	assign		wire_l1_w18_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[50] : data_wire[18];
	assign		wire_l1_w19_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[51] : data_wire[19];
	assign		wire_l1_w1_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[33] : data_wire[1];
	assign		wire_l1_w20_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[52] : data_wire[20];
	assign		wire_l1_w21_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[53] : data_wire[21];
	assign		wire_l1_w22_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[54] : data_wire[22];
	assign		wire_l1_w23_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[55] : data_wire[23];
	assign		wire_l1_w24_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[56] : data_wire[24];
	assign		wire_l1_w25_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[57] : data_wire[25];
	assign		wire_l1_w26_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[58] : data_wire[26];
	assign		wire_l1_w27_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[59] : data_wire[27];
	assign		wire_l1_w28_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[60] : data_wire[28];
	assign		wire_l1_w29_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[61] : data_wire[29];
	assign		wire_l1_w2_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[34] : data_wire[2];
	assign		wire_l1_w30_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[62] : data_wire[30];
	assign		wire_l1_w31_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[63] : data_wire[31];
	assign		wire_l1_w3_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[35] : data_wire[3];
	assign		wire_l1_w4_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[36] : data_wire[4];
	assign		wire_l1_w5_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[37] : data_wire[5];
	assign		wire_l1_w6_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[38] : data_wire[6];
	assign		wire_l1_w7_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[39] : data_wire[7];
	assign		wire_l1_w8_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[40] : data_wire[8];
	assign		wire_l1_w9_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[41] : data_wire[9];
	assign
		data_wire = {data},
		result = result_wire_ext,
		result_wire_ext = {wire_l1_w31_n0_mux_dataout, wire_l1_w30_n0_mux_dataout, wire_l1_w29_n0_mux_dataout, wire_l1_w28_n0_mux_dataout, wire_l1_w27_n0_mux_dataout, wire_l1_w26_n0_mux_dataout, wire_l1_w25_n0_mux_dataout, wire_l1_w24_n0_mux_dataout, wire_l1_w23_n0_mux_dataout, wire_l1_w22_n0_mux_dataout, wire_l1_w21_n0_mux_dataout, wire_l1_w20_n0_mux_dataout, wire_l1_w19_n0_mux_dataout, wire_l1_w18_n0_mux_dataout, wire_l1_w17_n0_mux_dataout, wire_l1_w16_n0_mux_dataout, wire_l1_w15_n0_mux_dataout, wire_l1_w14_n0_mux_dataout, wire_l1_w13_n0_mux_dataout, wire_l1_w12_n0_mux_dataout, wire_l1_w11_n0_mux_dataout, wire_l1_w10_n0_mux_dataout, wire_l1_w9_n0_mux_dataout, wire_l1_w8_n0_mux_dataout, wire_l1_w7_n0_mux_dataout, wire_l1_w6_n0_mux_dataout, wire_l1_w5_n0_mux_dataout, wire_l1_w4_n0_mux_dataout, wire_l1_w3_n0_mux_dataout, wire_l1_w2_n0_mux_dataout, wire_l1_w1_n0_mux_dataout, wire_l1_w0_n0_mux_dataout},
		sel_wire = {sel[0]};
endmodule //element_mux_32x2_mux
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module element_mux_32x2 (
	data0x,
	data1x,
	sel,
	result)/* synthesis synthesis_clearbox = 1 */;

	input	[31:0]  data0x;
	input	[31:0]  data1x;
	input	  sel;
	output	[31:0]  result;

	wire [31:0] sub_wire0;
	wire [31:0] sub_wire5 = data0x[31:0];
	wire [31:0] result = sub_wire0[31:0];
	wire  sub_wire1 = sel;
	wire  sub_wire2 = sub_wire1;
	wire [31:0] sub_wire3 = data1x[31:0];
	wire [63:0] sub_wire4 = {sub_wire5, sub_wire3};

	element_mux_32x2_mux	element_mux_32x2_mux_component (
				.sel (sub_wire2),
				.data (sub_wire4),
				.result (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Stratix III"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: CONSTANT: LPM_SIZE NUMERIC "2"
// Retrieval info: CONSTANT: LPM_TYPE STRING "LPM_MUX"
// Retrieval info: CONSTANT: LPM_WIDTH NUMERIC "32"
// Retrieval info: CONSTANT: LPM_WIDTHS NUMERIC "1"
// Retrieval info: USED_PORT: data0x 0 0 32 0 INPUT NODEFVAL data0x[31..0]
// Retrieval info: USED_PORT: data1x 0 0 32 0 INPUT NODEFVAL data1x[31..0]
// Retrieval info: USED_PORT: result 0 0 32 0 OUTPUT NODEFVAL result[31..0]
// Retrieval info: USED_PORT: sel 0 0 0 0 INPUT NODEFVAL sel
// Retrieval info: CONNECT: result 0 0 32 0 @result 0 0 32 0
// Retrieval info: CONNECT: @data 1 1 32 0 data1x 0 0 32 0
// Retrieval info: CONNECT: @data 1 0 32 0 data0x 0 0 32 0
// Retrieval info: CONNECT: @sel 0 0 1 0 sel 0 0 0 0
// Retrieval info: LIBRARY: lpm lpm.lpm_components.all
// Retrieval info: GEN_FILE: TYPE_NORMAL element_mux_32x2.tdf TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL element_mux_32x2.inc TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL element_mux_32x2.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL element_mux_32x2.bsf TRUE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL element_mux_32x2_inst.tdf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL element_mux_32x2_syn.v TRUE
// Retrieval info: LIB_FILE: lpm
